notifications:
  email:
    recipients:
      - fcalcagno@ciandt.com

language: node_js

node_js:
  - 14.18.1

before_script:
  - npm install

script:
  - npm run test:headless

before_deploy:
  - npm run build:prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/my-first-project
  on:
    branch: gh-pages